spring:
  application:
    name:api-gateway
eureka:
  client:
    serviceUrl:
      defaultZone:http://localhost:8761/eureka
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE
